include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/_legacy/**
    - lib/**/state/estimate_controller_legacy.dart
    - lib/**/state/estimate_controller_wiring.dart
    - test_legacy/**
    - packages/domain/analysis_options.yaml

linter:
  rules:
    require_trailing_commas: true