name: buildwise_clean
description: BuildWise Flutter app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0

  # 3rd‑party
  provider: ^6.1.5
  uuid: ^4.5.1
  intl: ^0.20.2
  pdf: ^3.11.1
  printing: ^5.12.0
  http: ^1.2.2
  file_picker: ^8.3.7
  shared_preferences: ^2.2.2
  path_provider: ^2.1.4
  share_plus: ^10.1.4

  # Firebase (you’re using these in iOS pods)
  firebase_crashlytics: ^4.1.3
  firebase_core: ^3.15.2
  firebase_analytics: ^11.6.0

  # Local packages
  buildwise_domain:
    path: packages/domain
  buildwise_data:
    path: packages/data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/cost_catalog_gh.json
    - assets/data/ghana_locations.json
    - assets/images/
    - assets/fonts/NotoSans-Regular.ttf
    - assets/fonts/NotoSans-Bold.ttf

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700