// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFeKLWcvjJ3kjIXas0gYQslsCGSb4kcaQ',
    appId: '1:329020058091:web:6e139995fb76c26d4691ae',
    messagingSenderId: '329020058091',
    projectId: 'building-estimator',
    authDomain: 'building-estimator.firebaseapp.com',
    storageBucket: 'building-estimator.firebasestorage.app',
    measurementId: 'G-69KNDHWYVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEW4ZS59Seo5eox--NMmiLu5iqurns694',
    appId: '1:329020058091:android:06523be7f4b6fa974691ae',
    messagingSenderId: '329020058091',
    projectId: 'building-estimator',
    storageBucket: 'building-estimator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtMGwUy-XJUAcC1GZZmuP902KiDh7DUCg',
    appId: '1:329020058091:ios:57ff5c552e5395114691ae',
    messagingSenderId: '329020058091',
    projectId: 'building-estimator',
    storageBucket: 'building-estimator.firebasestorage.app',
    iosBundleId: 'com.example.buildwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtMGwUy-XJUAcC1GZZmuP902KiDh7DUCg',
    appId: '1:329020058091:ios:71a579240b3169b64691ae',
    messagingSenderId: '329020058091',
    projectId: 'building-estimator',
    storageBucket: 'building-estimator.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFeKLWcvjJ3kjIXas0gYQslsCGSb4kcaQ',
    appId: '1:329020058091:web:7dae740638f510944691ae',
    messagingSenderId: '329020058091',
    projectId: 'building-estimator',
    authDomain: 'building-estimator.firebaseapp.com',
    storageBucket: 'building-estimator.firebasestorage.app',
    measurementId: 'G-T73118PNSZ',
  );

}