name: buildwise_domain
description: Domain layer for BuildWise (entities, use cases, repo interfaces)
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.3